#!/bin/bash
RANDOM_VAR=123564891
PARKINSONS="DAT/parkinsons.arff"
OZONE="DAT/ozone-320.arff"
HEART="DAT/spectf-heart.arff"

echo "AGG_BLX - PARKINSONS: "
./BIN/AGG_BLX $PARKINSONS $RANDOM_VAR >> AGG_BLX_PARKINSONS.dat

echo "AGG_BLX - OZONE: "
./BIN/AGG_BLX $OZONE $RANDOM_VAR >> AGG_BLX_OZONE.dat

echo "AGG_BLX - SPECIFIC-HEART: "
./BIN/AGG_BLX $HEART $RANDOM_VAR >> AGG_BLX_HEART.dat

echo "AGE_BLX - PARKINSONS: "
./BIN/AGE_BLX $PARKINSONS $RANDOM_VAR >> AGE_BLX_PARKINSONS.dat

echo "AGE_BLX - OZONE: "
./BIN/AGE_BLX $OZONE $RANDOM_VAR >> AGE_BLX_OZONE.dat

echo "AGE_BLX - SPECIFIC-HEART: "
./BIN/AGE_BLX $HEART $RANDOM_VAR >> AGE_BLX_HEART.dat

echo "AGG_CA - PARKINSONS: "
./BIN/AGG_CA $PARKINSONS $RANDOM_VAR >> AGG_CA_PARKINSONS.dat

echo "AGG_CA - OZONE: "
./BIN/AGG_CA $OZONE $RANDOM_VAR >> AGG_CA_OZONE.dat

echo "AGG_CA - SPECIFIC-HEART: "
./BIN/AGG_CA $HEART $RANDOM_VAR >> AGG_CA_HEART.dat

echo "AGE_CA - PARKINSONS: "
./BIN/AGE_CA $PARKINSONS $RANDOM_VAR >> AGE_CA_PARKINSONS.dat

echo "AGE_CA - OZONE: "
./BIN/AGE_CA $OZONE $RANDOM_VAR >> AGE_CA_OZONE.dat

echo "AGE_CA - SPECIFIC-HEART: "
./BIN/AGE_CA $HEART $RANDOM_VAR >> AGE_CA_HEART.dat

echo "AM_10_01 - PARKINSONS: "
./BIN/AM_10_01 $PARKINSONS $RANDOM_VAR  >> AM_10_01_PARKINSONS.dat

echo "AM_10_01 - OZONE: "
./BIN/AM_10_01 $OZONE $RANDOM_VAR  >> AM_10_01_OZONE.dat

echo "AM_10_01 - SPECIFIC-HEART: "
./BIN/AM_10_01 $HEART $RANDOM_VAR  >> AM_10_01_HEART.dat



echo "AM_10_01mej - PARKINSONS: "
./BIN/AM_10_01mej $PARKINSONS $RANDOM_VAR >> AM_10_01mej_PARKINSONS.dat

echo "AM_10_01mej - OZONE: "
./BIN/AM_10_01mej $OZONE $RANDOM_VAR >> AM_10_01mej_OZONE.dat

echo "AM_10_01mej - SPECIFIC-HEART: "
./BIN/AM_10_01mej $HEART $RANDOM_VAR >> AM_10_01mej_HEART.dat

echo "AM_10_1 - PARKINSONS: "
./BIN/AM_10_1 $PARKINSONS $RANDOM_VAR >> AM_10_1_PARKINSONS.dat

echo "AM_10_1 - OZONE: "
./BIN/AM_10_1 $OZONE $RANDOM_VAR  >> AM_10_1_OZONE.dat

echo "AM_10_1 - SPECIFIC-HEART: "
./BIN/AM_10_1 $HEART $RANDOM_VAR  >> AM_10_1_HEART.dat



echo "LocalSearch - SPECIFIC-HEART: "
./BIN/LocalSearch $HEART $RANDOM_VAR  >> LocalSearch_HEART.dat

echo "LocalSearch - PARKINSONS: "
./BIN/LocalSearch $PARKINSONS $RANDOM_VAR  >> LocalSearch_PARKINSONS.dat

echo "LocalSearch - OZONE: "
./BIN/LocalSearch $OZONE $RANDOM_VAR  >> LocalSearch_OZONE.dat

echo "RELIEF - PARKINSONS: "
./BIN/RELIEF $PARKINSONS >> RELIEF_PARKINSONS.dat

echo "RELIEF - OZONE: "
./BIN/RELIEF $OZONE >> RELIEF_OZONE.dat

echo "RELIEF - SPECIFIC-HEART: "
./BIN/RELIEF $HEART >> RELIEF_HEART.dat

echo "Clasificador1NN - PARKINSONS: "
./BIN/Clasificador1NN $PARKINSONS >> Clasificador1NN_PARKINSONS.dat

echo "Clasificador1NN - OZONE: "
./BIN/Clasificador1NN $OZONE >> Clasificador1NN_OZONE.dat

echo "Clasificador1NN - SPECIFIC-HEART: "
./BIN/Clasificador1NN $HEART >> Clasificador1NN_HEART.dat
