% GSA code v1.1.
% Generated by Esmat Rashedi, 2010. 
% " E. Rashedi, H. Nezamabadi-pour and S. Saryazdi,
%�GSA: A Gravitational Search Algorithm�, Information sciences, vol. 179,
%no. 13, pp. 2232-2248, 2009."
%
% This function calculates Gravitational constant. eq.13.
function G=Gconstant(iteration,max_it)
%%%here, make your own function of 'G'8

  alfa=20;
  G0=100;
  
  G=G0*exp(-alfa*iteration/max_it); %eq. 28.
  
  %G = GN + (G0 - GN) * (1 / (1 + exp(log(G0 - GN) * iteration * 0.5 * max_it)));
  %G = GN + 0.5 * (G0 - GN) * (1 + cos(iteration * pi / max_it));